<a href="https://colab.research.google.com/github/sudaltokki/ML_STUDY/blob/main/Miday/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor**

In [ ]:
import numpy as np
import torch

텐서 생성

In [ ]:
# 중첩 list를 지정
t = torch.tensor([[1,2],[3,4.]])

In [ ]:
# device를 지정하면 GPU에 텐서를 만들 수 있다
t = torch.tensor([[1,2],[3,4.]], device="cuda:0")

In [ ]:
# dtype를 사용해 데이터형을 지정하여 텐서를 만들 수 있다
t = torch.tensor([[1,2],[3,4.]], dtype=torch.float64)

In [ ]:
# 0부터 9까지 수치로 초기화된 1차원 텐서
t = torch.arange(0,10)

In [ ]:
# 모든 값이 0인 100*10의 테서를 작성해서 to 메서드로 GPU에 전송
t = torch.zeros(100,10).to("cuda:0")

In [ ]:
# 정규 난수로 100*10의 텐서를 작성
t = torch.randn(100,10)

In [ ]:
# 텐서의 shape은 size 메서드로 확인 가능
t.size()

torch.Size([100, 10])

텐서 변환

In [ ]:
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1, 2],[3, 4.]])
x = t.numpy()

In [ ]:
# GPU상의 텐서는 to 메서드로, CPU의 텐서로 이동(변환)할 필요가 있다
t = torch.tensor([[1, 2],[3, 4.]], device="cuda:0")
x = t.to("cpu").numpy()

텐서의 인덱스 조작

In [ ]:
t = torch.tensor([[1,2,3],[4,5,6.]])

In [ ]:
# 스칼라 첨자 지정
t[0,2]

tensor(3.)

In [ ]:
# 슬라이스로 지정
t[:,:2]

tensor([[1., 2.],
        [4., 5.]])

In [ ]:
# 리스트로 지정
t[:,[1,2]]

tensor([[2., 3.],
        [5., 6.]])

In [ ]:
# [0,1]의 요소를 100으로 설정
t[0,1] = 100

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])

In [ ]:
# 슬라이스를 사용한 일괄 대입
t[:,1] = 200

tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])

In [ ]:
# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t>10] = 20

tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])

텐서 연산

In [ ]:
# 길이 3인 벡터
v = torch.tensor([1,2,3.])
w = torch.tensor([0,10,20.])
# 2*3의 행렬
m = torch.tensor([[0,1,2.],[100,200,300.]])

In [ ]:
# 벡터와 스칼라의 덧셈
v2 = v + 10

tensor([11., 12., 13.])

In [ ]:
# 제곱도 같은 방식
v2 = v ** 2

tensor([1., 4., 9.])

In [ ]:
# 동일 길이의 벡터 간 뺄셈
z = v - w

tensor([  1.,  -8., -17.])

In [ ]:
# 여러 가지 조합
u = 2 * v - w / 10 + 6.0

tensor([ 8.,  9., 10.])

In [ ]:
# 행렬과 스칼라
m2 = m * 2.0

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])

In [ ]:
# 행렬과 벡터
# (2, 3)인 행렬과 (3,)인 벡터이므로 브로드캐스트가 작동
m3 = m + v

tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])

In [ ]:
# 행렬 간 처리
m4 = m + m

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])

수학 함수

In [ ]:
# 100*10의 테스트 데이터 생성
X = torch.randn(100,10)

In [ ]:
# 수학 함수를 포함하는 수식
y = X * 2 + torch.abs(X)

In [ ]:
# 평균치 구하기
m = torch.mean(X)
# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()

tensor(0.0017)

In [ ]:
# 집계 결과는 0차원의 텐서로 item 메서드를 사용해서 값을 추출할 수 있다
m_value = m.item()

0.0016544440295547247

In [ ]:
# 집계는 차원을 지정할 수 있다. 다음은 행 방향으로 집계해서, 열 단위로 평균값을 계산한다
m2 = X.mean(0)

tensor([-0.1014,  0.0584,  0.1421,  0.0080, -0.0668,  0.0662, -0.1623,  0.0378,
         0.0565, -0.0219])

텐서의 인덱스 조작

In [ ]:
x1 = torch.tensor([[1,2],[3,4.]]) # 2*2
x2 = torch.tensor([[10,20,30],[40,50,60.]]) # 2*3 

In [ ]:
# 2*2를 4*1로 보여준다
x1.view(4,1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [ ]:
# -1은 표현할 수 있는 자동화된 값으로 대체되며, 한 번만 사용할 수 있다. 아래 예에선 -1을 사용하면 자동으로 4가 된다
x1.view(1,-1)

tensor([[1., 2., 3., 4.]])

In [ ]:
# 2*3을 전치해서 3*2로 만든다
x2.t()

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])

In [ ]:
# dim=1로 결합하면 2*5의 텐서를 만든다
torch.cat([x1,x2],dim=1)

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [ ]:
# HWC(높이, 너비, 색)를 CHW(색, 높이, 너비)로 변환
# 64*32*3의 데이터가 100개
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1,2).transpose(1,3)



*   dot: 벡터 내적
*   mv: 행렬과 벡터의 곱
*   mm: 행렬과 행렬의 곱
*   matmul: 인수의 종류에 따라 자동으로 dot, mv, mm을 선택해서 실행
*   gesv: LU 분해를 사용한 연립 방정식의 해
*   eig, symeig: 고유값 분해, symeig는 대칭 행렬보다 효율이 좋은 알고리즘
*   svd: 특이값 분해



선형 대수 연산

In [ ]:
m = torch.randn(100,10)
v = torch.randn(10)

In [ ]:
# 내적
d = torch.dot(v,v)

tensor(9.6564)

In [ ]:
# 100*10의 행렬과 길이 10인 벡터의 곱. 결과는 길이 100인 벡터
v2 = torch.mv(m,v)

tensor([ 0.4069,  5.7904,  3.2561,  3.3384,  5.3324,  3.3465, -1.2255,  2.3690,
         2.7487,  1.4148,  2.3482,  1.0583, -2.9924, -1.8135,  8.0294, -4.0355,
         2.0914,  2.5001,  1.4544, -2.1551,  1.4343, -1.3190, -0.1646,  3.7672,
         0.6057,  3.7425, -1.9217,  3.2749, -2.9405,  2.9033, -1.0100,  3.5686,
        -2.0592,  1.1731,  1.5397,  2.2251, -3.3635,  1.0194, -3.4333,  2.9572,
        -3.9494,  0.2499,  2.0215,  2.6004,  5.1248,  3.5037,  2.4964,  3.4239,
        -0.5314, -1.1112,  5.5699,  4.1204,  6.5778,  0.9430, -6.7062, -0.4561,
        -3.3485, -2.2957,  3.2843,  4.5080, -7.4255,  5.5402,  0.9674, -3.2350,
         1.6327, -2.4147, -1.3809,  4.4467, -1.4071,  0.3381,  0.7026,  3.0297,
         1.1024,  0.5028, -0.2648,  4.5075,  1.0065,  2.3970,  1.7114,  1.3730,
         4.9459,  2.6194, -1.8991,  0.5459,  0.9873,  3.8411, -4.5090, -4.1979,
        -2.0638, -0.7332, -1.6071, -1.5652, -6.1801, -1.9065,  4.1446,  1.3598,
         8.5009,  6.0658, -2.1851, -6.92

In [ ]:
# 행렬곱
m2 = torch.mm(m.t(),m)

tensor([[ 9.9847e+01,  6.0712e+00, -5.7159e+00, -4.0354e+00, -1.1215e+01,
         -1.8800e+01,  4.3084e+00, -5.2909e-01,  1.6216e+01,  3.0195e+00],
        [ 6.0712e+00,  1.1944e+02,  1.6344e+01, -7.2349e-02, -7.2224e+00,
          2.2491e+00,  1.8358e+01, -2.1413e+00,  9.2520e+00, -5.3541e+00],
        [-5.7159e+00,  1.6344e+01,  9.5214e+01,  6.8481e+00, -7.5125e-01,
         -6.6878e+00,  1.5643e+01, -6.8507e+00, -1.4903e+01, -5.6057e+00],
        [-4.0354e+00, -7.2349e-02,  6.8481e+00,  1.1378e+02,  4.7633e+00,
         -1.0774e-01, -1.2896e+00,  5.7509e+00, -4.4964e-01,  1.0761e+01],
        [-1.1215e+01, -7.2224e+00, -7.5125e-01,  4.7633e+00,  9.1019e+01,
         -1.4247e+00, -5.2610e+00, -1.3594e+01,  5.5237e+00, -2.6552e+01],
        [-1.8800e+01,  2.2491e+00, -6.6878e+00, -1.0774e-01, -1.4247e+00,
          1.0083e+02, -5.6614e+00,  7.0608e+00, -2.9775e+00,  5.9227e+00],
        [ 4.3084e+00,  1.8358e+01,  1.5643e+01, -1.2896e+00, -5.2610e+00,
         -5.6614e+00,  9.2138e+0

In [ ]:
# 특이값 분해
u, s, v = torch.svd(m)

tensor([[-0.0148,  0.3640, -0.4479,  0.0159, -0.3519,  0.2115, -0.4216,  0.0472,
          0.4728, -0.3072],
        [ 0.2261,  0.6729,  0.1980, -0.0108,  0.3975,  0.3410,  0.1886,  0.3686,
         -0.0868, -0.0592],
        [ 0.2169,  0.2212,  0.4546,  0.0299, -0.2153, -0.1214,  0.3247, -0.4539,
          0.5603,  0.1002],
        [-0.1576,  0.0256,  0.3088,  0.8701, -0.0961,  0.1007, -0.2834,  0.0692,
         -0.0618,  0.1169],
        [ 0.3066, -0.3140, -0.0738,  0.3210,  0.1573, -0.1070,  0.3134,  0.1159,
          0.1283, -0.7312],
        [-0.1601, -0.1695,  0.2344, -0.1381,  0.6689,  0.1242, -0.4694, -0.2681,
          0.3103, -0.1423],
        [ 0.2183,  0.3534,  0.1689, -0.0660, -0.0627, -0.5610, -0.3821, -0.2383,
         -0.4188, -0.3127],
        [-0.4619,  0.1507,  0.0193,  0.0061,  0.1433, -0.6323,  0.0931,  0.4671,
          0.3389,  0.0391],
        [-0.0192,  0.2430, -0.5964,  0.3353,  0.3901, -0.1618,  0.2073, -0.4518,
         -0.0321,  0.2142],
        [-0.7042,  

텐서와 자동 미분

In [ ]:
x = torch.randn(100,3)
# 미분의 변수로 사용하는 경우는 requires_grad를 True로 설정
a = torch.tensor([1,2,3.],requires_grad=True)

In [ ]:
# 계산을 통해 자동으로 계산 그래프가 구축된다
y = torch.mv(x,a)
o = y.sum()

In [ ]:
# 미분을 실행
o.backward()

In [ ]:
# 분석 답과 비교
a.grad != x.sum(0) # 이 부분 질문

tensor([True, True, True])

In [ ]:
# x는 requires_grad가 False이므로 미분이 계산되지 않는다
x.grad is None

True